language: node_js # don't install any environment

dist: xenial

node_js:
- "node"

os:
- linux
- osx
# - windows # Integration tests are failing on windows

osx_image: xcode11.3

matrix:
  include:
    - os: linux
      node_js:
        - "10"
