language: node_js # don't install any environment

node_js:
- "node"

os:
- linux
- osx
# - windows # Integration tests are failing on windows

matrix:
  include:
    - os: linux
      node_js:
        - "10"
    - os: linux
      node_js:
        - "8"
